services:
    giantbomb.config:
        class: DBorsatto\GiantBomb\Config
        arguments: [ "%giantbomb.api_key%" ]
    giantbomb.client:
        class: DBorsatto\GiantBomb\Client
        arguments: [ "@giantbomb.config" ]
